# Generated by Django 6.1 on 2026-08-31 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='mentee',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='task',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
