# Generated by Django 6.1 on 2026-09-01 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_remove_submission_mentee_remove_submission_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['mentor', '-created_at'], name='mentorship__mentor__d8eeae_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['status', 'start_time', 'end_time'], name='mentorship__status_b6e6e7_idx'),
        ),
    ]
