# Generated by Django 6.1 on 2026-09-03 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0003_alter_feedback_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mentorship',
            name='unique_active_mentorship',
        ),
        migrations.AddField(
            model_name='schedule',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('COMPLETED', 'Đã hoàn thành'), ('CANCELLED', 'Đã hủy')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Đang chờ'), ('ACCEPTED', 'Đã chấp nhận'), ('REJECTED', 'Đã từ chối'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='mentorship',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('mentee', 'mentor'), name='unique_active_mentorship'),
        ),
    ]
